language: python
python:
  - "3.6"
before_install:
  - mv travis/travis_secrets.yaml secrets.yaml
  - mv travis/fake_ssl_crt.pem travis.fake_ssl_crt.pem
  - mv travis/fake_ssl_key.pem travis.fake_ssl_key.pem
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config