########################################################
# HA Main Config Block
########################################################
homeassistant:
  name: Home
  latitude: !secret loc_latitude_home
  longitude: !secret loc_longitude_home
  elevation: !secret loc_elevation_home
  unit_system: imperial
  time_zone: America/Denver
  packages: !include_dir_named packages
  auth_providers:
   - type: homeassistant
   - type: trusted_networks

########################################################
# Enabled components
########################################################
config:
custom_updater:
  track:
    - cards
    - components
    - python_scripts
  hide_sensor: true
  show_installable: false
  # card_urls:
  #   - 
  component_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  python_script_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/python_scripts.json
discovery:
  ignore:
    # - apple_tv
    # - google_cast
    # - plex_mediaserver
    - philips_hue
    # - roku
ffmpeg:
frontend:
  javascript_version: auto
  themes: !include includes/themes.yaml
geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: 'past_day_all_earthquakes'
history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - binary_sensor.homenas_freespace_1_low
      - binary_sensor.homenas_freespace_2_low
http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ssl_profile: intermediate  # should be the default imho
  trusted_networks:
    - !secret trusted_network_ip_range
  cors_allowed_origins:
    - !secret duckdns_url
    - !secret local_url_1
    - !secret local_url_2
ios:
logbook:
lovelace:
  mode: yaml
map:
recorder:
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true
shell_command:
  lovelace_gen: 'python /config/lovelace-gen.py'
zeroconf:

weblink:
  entities:
    - name: Grafana
      url: !secret grafana_url
    - name: Node-red
      url: !secret node_red_url
    - name: Router
      url: !secret router_url

########################################################
# Logger
########################################################
logger:
  default: warn
  logs:
    homeassistant.components.mqtt: debug

########################################################
# Panels
########################################################
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

########################################################
# Text to Speech
########################################################
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

########################################################
# InfluxDB
########################################################
influxdb:
  host: home-nas
  default_measurement: state
  tags_attributes:
    - friendly_name
  exclude:
    domains:
      - group
      - persistent_notification
    entities:
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daily_high_temperature_0
      - sensor.dark_sky_daily_low_temperature_0
      - sensor.dark_sky_temperature
      - sensor.dark_sky_temperature_0

########################################################
# Cloud
########################################################
cloud:
  alexa:
    filter:
      include_domains:
        - group
        - light
        - switch

########################################################
# MQTT
########################################################
mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password
  # port: 8883
  # certificate: auto

########################################################
# Climate, weather & sun
########################################################
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
sun:


########################################################
# Standard includes
########################################################
automation: !include automations.yaml
group: !include includes/group.yaml
script: !include includes/script.yaml
sensor: !include includes/sensor.yaml
zone: !include includes/zones.yaml
