shell_command:
  secrets_backup: bash /config/secrets_backup.sh

automation:
  - alias: "Utility - Backup secrets every night at 10pm"
    trigger:
      - platform: time
        at: "10:00:00"
    action:
      - service: shell_command.secrets_backup