# See https://github.com/shortbloke/home_assistant_config/blob/master/docs/build_deploy.md

sensor:
  - platform: travisci
    api_key: !secret github_access_token
    repository:
      - homeassistant-config
    monitored_conditions:
      - last_build_id
      - last_build_state

# Available sensor names for automation
# sensor.pprovosthomeassistantconfig_last_build_id
# sensor.pprovosthomeassistantconfig_last_build_state

automation:
  - alias: Update config HASS if travis build is successfull
    trigger:
      - platform: state
        entity_id: sensor.pprovosthomeassistantconfig_last_build_state
        from: 'started'
        to: 'passed'
    action:
      # - service: shell_command.secrets_backup
      # - delay:
      #     minutes: 1
      - service: persistent_notification.create
        data:
          message: "Travis triggered"
          title: "Travis Triggered"
          notification_id: travis_triggered
      - service: hassio.addon_restart
        data: 
          addon: 'core_git_pull'