sensor:
  - platform: travisci
    api_key: !secret github_access_token
    repository:
      - homeassistant-config
    branch: master
    monitored_conditions:
      - last_build_id
      - last_build_state

automation:
  - alias: Update from github if travis last_build_state changes
    trigger:
      - platform: state
        entity_id: sensor.pprovost_homeassistant_config_last_build_state
        from: 'started'
        to: 'passed'
    action:
      - service: persistent_notification.create
        data:
          message: "Travis build succeeded. Initiating 'git pull'. Will restart when complete."
          title: "Travis Build Succeeded"
          notification_id: travis_triggered_state
      - service: hassio.addon_restart
        data:
          addon: core_git_pull

