# See https://github.com/shortbloke/home_assistant_config/blob/master/docs/build_deploy.md

sensor:
  - platform: travisci
    api_key: !secret github_access_token
    repository:
      - homeassistant-config
    monitored_conditions:
      - last_build_id
      - last_build_state

# Available sensor names for automation
# sensor.pprovosthomeassistantconfig_last_build_id
# sensor.pprovosthomeassistantconfig_last_build_state

automation:
  - alias: Update from github if travis last_build_state changes
    trigger:
      - platform: state
        entity_id: sensor.pprovosthomeassistantconfig_last_build_state
        to: 'passed'
    action:
      - service: persistent_notification.create
        data:
          message: "Travis triggered"
          title: "Travis Triggered (Last Build State)"
          notification_id: travis_triggered_state

  - alias: Update from github if travis last_build_id changes
    trigger:
      - platform: state
        entity_id: sensor.pprovosthomeassistantconfig_last_build_id
    action:
      - service: persistent_notification.create
        data:
          message: "Travis triggered (Last Build Id)"
          title: "Travis Triggered"
          notification_id: travis_triggered_id
