homeassistant:
  customize:
    binary_sensor.x3_xdrive30i_check_control_messages:
      friendly_name: X3 Check Ctl Msgs
    binary_sensor.x3_xdrive30i_condition_based_services:
      friendly_name: X3 Cond. based svcs
    binary_sensor.x3_xdrive30i_door_lock_state:
      friendly_name: X3 Door Lock State
    binary_sensor.x3_xdrive30i_lids:
      friendly_name: X3 Lids
    binary_sensor.x3_xdrive30i_lights_parking:
      friendly_name: X3 Lights Parking
    binary_sensor.x3_xdrive30i_windows:
      friendly_name: X3 Windows State
    lock.x3_xdrive30i_lock:
      friendly_name: X3 Door Locks
    sensor.x3_xdrive30i_mileage:
      friendly_name: X3 Mileage
    sensor.x3_xdrive30i_remaining_fuel:
      friendly_name: X3 Remaining Fuel
    sensor.x3_xdrive30i_remaining_range_fuel:
      friendly_name: X3 Remaining Range Fuel
    sensor.x3_xdrive30i_remaining_range_total:
      friendly_name: X3 Remaining Range Total

bmw_connected_drive:
  name:
    username: !secret bmw_connected_drive_username
    password: !secret bmw_connected_drive_password
    region: "north_america"

binary_sensor:
  - platform: template
    sensors:
      x3_xdrive30i_oil_status_ok:
        value_template: "{{ not is_state_attr('binary_sensor.x3_xdrive30i_condition_based_services', 'oil status', 'OK') }}"
        friendly_name: "Oil status okay?"
        device_class: safety

      x3_xdrive30i_vehicle_check_status_ok:
        value_template: "{{ not is_state_attr('binary_sensor.x3_xdrive30i_condition_based_services', 'vehicle check status', 'OK') }}"
        friendly_name: "Vehicle check status okay?"
        device_class: safety

      x3_xdrive30i_brake_fluid_status_ok:
        value_template: "{{ not is_state_attr('binary_sensor.x3_xdrive30i_condition_based_services', 'brake fluid status', 'OK') }}"
        friendly_name: "Brake fluid status okay?"
        device_class: safety

sensor:
  - platform: template
    sensors:
      x3_xdrive30i_remaining_fuel_percent:
        value_template: '{{ (states("sensor.x3_xdrive30i_remaining_fuel")|float / 17.2 * 100) | round(0) }}'
        friendly_name: "Remaining Fuel %"
        unit_of_measurement: "%"
        device_class: battery

alert:
  bmw_oil_status_not_okay:
    name: "BMW alert - oil status not okay"
    message: "BMW alert - oil status not okay"
    done_message: "BMW alert - oil status alert done"
    entity_id: binary_sensor.x3_xdrive30i_oil_status_ok
    state: 'on'
    repeat:
      - 15
      - 30
      - 60
    notifiers:
      - telegram_peter  
  bmw_vehicle_check_not_okay:
    name: "BMW alert - vehicle check status not okay"
    message: "BMW alert - vehicle check status not okay"
    done_message: "BMW alert - vehicle check status alert done"
    entity_id: binary_sensor.x3_xdrive30i_vehicle_check_status_ok
    state: 'on'
    repeat:
      - 15
      - 30
      - 60
    notifiers:
      - telegram_peter  
  bmw_brake_fluid_status_not_okay:
    name: "BMW alert - brake fluid status not okay"
    message: "BMW alert - brake fluid status not okay"
    done_message: "BMW alert - brake fluid status alert done"
    entity_id: binary_sensor.x3_xdrive30i_brake_fluid_status_ok
    state: 'on'
    repeat:
      - 15
      - 30
      - 60
    notifiers:
      - telegram_peter  

group:
  all_bmw_entities:
    name: BMW X3
    entities:
      - binary_sensor.x3_xdrive30i_check_control_messages
      - binary_sensor.x3_xdrive30i_condition_based_services
      - binary_sensor.x3_xdrive30i_door_lock_state
      - binary_sensor.x3_xdrive30i_lids
      - binary_sensor.x3_xdrive30i_lights_parking
      - binary_sensor.x3_xdrive30i_windows
      - lock.x3_xdrive30i_lock
      - sensor.x3_xdrive30i_mileage
      - sensor.x3_xdrive30i_remaining_fuel
      - sensor.x3_xdrive30i_remaining_fuel_percent
      - sensor.x3_xdrive30i_remaining_range_fuel
      # - sensor.x3_xdrive30i_remaining_range_total