automation:
  - alias: "Garage lights - On when motion detected"
    trigger:
      - platform: state
        entity_id: binary_sensor.garage_motion_sensor
        to: 'on'
    action:
      service: switch.turn_on
      entity_id: switch.garage_lights

  - alias: "Garage lights - Off when no motion detected for 10m"
    trigger:
      - platform: state
        entity_id: binary_sensor.garage_motion_sensor
        to: 'off'
        for:
          minutes: 10
    action:
      service: switch.turn_off
      entity_id: switch.garage_lights

  - alias: "Garage lights - On when interior door opened"
    trigger:
      - platform: state
        entity_id: binary_sensor.garage_interior_door_contact_sensor
        to: 'on'
    action:
      service: switch.turn_on
      entity_id: switch.garage_lights
