- platform: template
  sensors:
    outside_temp:
        friendly_name: "Outside Temp"
        unit_of_measurement: "°F"
        device_class: temperature
        value_template: "{{ state_attr('weather.dark_sky', 'temperature') }}"