homeassistant:
  customize:
    sensor.home_assistant_srv_freespace:
      friendly_name: "node-red-pi Freespace"
    sensor.home_assistant_srv_temp:
      friendly_name: "node-red-pi Temp"

sensor:
  - platform: mqtt
    name: home_assistant_srv_freespace
    unit_of_measurement: "GB"
    state_topic: "network/node-red-pi/freespace"

  - platform: mqtt
    name: home_assistant_srv_temp
    device_class: temperature
    unit_of_measurement: "°C"
    state_topic: "network/node-red-pi/temp"
